package com.example.wuqi.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.wuqi.model.bean.ConcernBean;

import com.example.wuqi.db.ConcernBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig concernBeanDaoConfig;

    private final ConcernBeanDao concernBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        concernBeanDaoConfig = daoConfigMap.get(ConcernBeanDao.class).clone();
        concernBeanDaoConfig.initIdentityScope(type);

        concernBeanDao = new ConcernBeanDao(concernBeanDaoConfig, this);

        registerDao(ConcernBean.class, concernBeanDao);
    }
    
    public void clear() {
        concernBeanDaoConfig.clearIdentityScope();
    }

    public ConcernBeanDao getConcernBeanDao() {
        return concernBeanDao;
    }

}
